### ISSUE TITLE
Callout width larger than total screen width, breaks on smaller screens

### ISSUE THREAD

**Issue by emiltoteb** [josh-collinsworth/sveltekit-blog-starter#12]
**Problem:** The width of the `.callout` element is larger than the width of the screen, causing a resize and a white bar to appear on the right (visible in the header/footer of the page).

Root cause: [Line 5 of _components.scss](https://github.com/josh-collinsworth/sveltekit-blog-starter/blob/6ef1c7fb4fb1f73735813e3403e7c9c758ac8bf3/src/lib/assets/scss/_components.scss) - the max width is unset.

Potential Solutions:

- Change line 5 to `max-width: calc(100vw + 1rem);` - fixing the white bar on the right, but now having rounded corners visible only on the right side.
- Change lines 4 and 6 to `width: calc(100% + 2rem);` and `margin: 2rem -1rem 2rem -1rem;` accordingly, essentially making the callout fit the size of the screen. *This may require additional changes to the padding, depending on the desired look.

**Comment by josh-collinsworth** [comment]
Thanks for reporting! Should be fixed in the latest version.
