### ISSUE TITLE
error when trying to install NodeJS (modules) dependencies using npm

### ISSUE THREAD

**Issue by Hafeez00** [josh-collinsworth/sveltekit-blog-starter#21]
We are in the process of containerization a NodeJS application and running into an error when trying to install NodeJS (modules) dependencies using npm.  The error message says, “ECONNREFUSED” followed by the IP and 443 port number.
 
We initially thought that it might be due to the proxy configuration and set the proxy configuration to null; however, that has been ruled out and did not resolve the issue.
 
"npm config set proxy null
npm config set https-proxy null"
 
Please see the below contents of Dockerfile and the error message. 
 
Any help or guidance you can provide would be greatly appreciated. 
 
Thanks in advance! 
 
------------------------------------------------------------------------------ 
Dockerfile: 
 
FROM node
 
# Create app directory
RUN mkdir /app
WORKDIR /app
 
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
 
COPY package*.json /app
 
RUN npm cache clear --force
RUN npm cache verify
 
#RUN npm config set proxy null
#RUN npm config set https-proxy null
 
RUN npm config set registry https://registry.npmjs.org/ --global
RUN npm config set strict-ssl false
RUN npm set maxsockets 3
RUN npm -version
RUN node -v
 
#RUN npm install
RUN npm install -g [npm@9.1.2](mailto:npm@9.1.2)
 
# If you are building your code for production
# RUN npm ci --only=production
 
# Bundle app source
COPY . .
 
EXPOSE 5000
CMD [ "node", "app.js" ]
 
------------------------------------------------------------------------------
ERROR: 
 
STEP 12/15: RUN npm install -g [npm@9.1.2](mailto:npm@9.1.2)
npm ERR! code ECONNREFUSED
npm ERR! syscall connect
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to [https://registry.npmjs.org/npm](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.com%2Fv3%2F__https%3A%2Fregistry.npmjs.org%2Fnpm__%3B!!May37g!MAZKpsbuoJKZJLg83IYqKQqrj8v4RXcolb7SAGMvYRIHP3QuEEMNbJ62RWhribIE5mSv-vlKKdnfgd8c-j1b3qwBg1itboJ--p0%24&data=05%7C01%7Cmohammed.a.hafeez%40nasa.gov%7C5ea1581198c74760861308dad24336c4%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638053483369665006%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OIESFB%2FMwohkPFOBJ5klTiGa6VC7JxkX7KozDWcHBVw%3D&reserved=0) failed, reason: connect ECONNREFUSED 104.16.25.35:443
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:488:9)
npm ERR!     at TLSSocket.emit (node:events:525:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR!  FetchError: request to [https://registry.npmjs.org/npm](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.com%2Fv3%2F__https%3A%2Fregistry.npmjs.org%2Fnpm__%3B!!May37g!MAZKpsbuoJKZJLg83IYqKQqrj8v4RXcolb7SAGMvYRIHP3QuEEMNbJ62RWhribIE5mSv-vlKKdnfgd8c-j1b3qwBg1itboJ--p0%24&data=05%7C01%7Cmohammed.a.hafeez%40nasa.gov%7C5ea1581198c74760861308dad24336c4%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638053483369821318%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UlEzTWuTH22deUBreqkm9ylMr8SEYlw2eQP6n4KApL0%3D&reserved=0) failed, reason: connect ECONNREFUSED 104.16.25.35:443
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:488:9)
npm ERR!     at TLSSocket.emit (node:events:525:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '104.16.25.35',
npm ERR!   port: 443,
npm ERR!   type: 'system'
npm ERR! }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'
 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-29T18_24_19_209Z-debug-0.log
Error: error building at STEP "RUN npm install -g [npm@9.1.2](mailto:npm@9.1.2)": error while running runtime: exit status 1

**Comment by josh-collinsworth** [comment]
I wish I could help, but I'm sorry, this is way beyond the scope of what I have the ability to troubleshoot. That said: at a cursory look, it appears to me the issue is in connecting with NPM itself (or at least, how Docker is configured to connect to NPM), rather than anything specific to this project or repo. To my knowledge, there's nothing in this project that would even be capable of causing an error like this.

**Comment by Hafeez00** [comment]
No worries. Thank you for reading the post.
