### ISSUE TITLE
Pagination isn't working as expected

### ISSUE THREAD

**Issue by teonbrooks** [josh-collinsworth/sveltekit-blog-starter#22]
hey @josh-collinsworth, I've been working to get my blog up and running but I've noticed that the pagination isn't working as expected. On my blog, I have six entries, the second page is indicated, but when I click it, I get redirected to the first page. 
- https://alpha.teonbrooks.com/blog
- https://alpha.teonbrooks.com/api/posts/count

I also tried troubleshooting it with this original repo and I get the same redirect to the first page. any insights?

**Comment by josh-collinsworth** [comment]
Hmmm, I have a hunch. Let me check…

**Comment by josh-collinsworth** [comment]
@teonbrooks I found the issue. I want to take a little more time to get the fix working on my end, but you can solve the problem on your side by replacing this line in `src/routes/blog/page/[page]/+page.server.js`:

```js
  const page = Number.isFinite(params.page) ? params.page : 1
```

With this instead:

```js
  const page = parseInt(params.page) ? parseInt(params.page) : 1
```

There are other possible solutions, too. But to summarize the issue: `isFinite` fails when the input is a string (which the incoming page number is, being pulled directly from `params`. So it just got set as `1` constantly before.

That's a pretty big bug, so thanks for finding and reporting it! It also helped me realize pagination doesn't work on category pages, either. Yikes! I'll merge the fix to the original repo soon, but the above should work for you.

**Comment by teonbrooks** [comment]
thanks! I was eyeing that line but wasn't sure. it all makes sense after you explained that page is a string when it gets plucked from params
