### ISSUE TITLE
Update for sveltekit 1.0

### ISSUE THREAD

**Issue by godber** [josh-collinsworth/sveltekit-blog-starter#23]
This is a great example!  Do you have any plans on updating this for the recent release of sveltekit 1.0?

**Comment by lakebayagency** [comment]
Awesome.  Looking forward to using this with the SK 1.0 release!

Should the PR include a quick edit to the README (the part talking about using the pre-release version of SK)?

**Comment by godber** [comment]
Good suggestion, I'd be happy to update the README if there's any chance of this getting merged.

**Comment by josh-collinsworth** [comment]
Thanks for the PR @godber! I just merged it, and added some on top of it to update the README.

**Comment by lakebayagency** [comment]
Lovely! :)

I'm using this project as a base for a new project!
