### ISSUE TITLE
Prerendered content generates initial 500 status, then 200 on refresh

### ISSUE THREAD

**Issue by lakebayagency** [josh-collinsworth/sveltekit-blog-starter#26]
I cloned the repo today (the version that includes the PR to update deps to SK 1.0), installed the dependencies, committed and pushed to github.

Then I set up a project in vercel.  I did nothing to the settings - build defaults to detecting SvelteKit and I adjusted none of the commands.  I deployed.

Home page looks great! :)

But when I click on the blog link, I get a 500 error.

On refresh, the page renders as expected.

The same happens with every post inside of this page - initial 500, then displays.

This doesn't happen locally.

My next step is to test a local build and preview, but I'm running out of time this morning and wanted to get this issue written first.

I'll update with additional findings.

**Comment by lakebayagency** [comment]
OK, my curiosity was greater than my reluctance to be late. :)

I build and previewed locally and there is no problem.

So I suspect there is a problem in the default settings of the vercel project.  Will update as I know more.

**Comment by lakebayagency** [comment]
Dialed down node from default of 18,x to 16.x - no change.

Tried switching to the SvelteKit (Legacy Build) detector - no change.

**Comment by lakebayagency** [comment]
Ah - it's the nav link itself - visiting the blog endpoint directly avoids the error.

**Comment by lakebayagency** [comment]
I've looked around in the NavItem and related files, but I don't see why anything there would cause a problem.  The NavItem generates what seems to be a pretty vanilla anchor tag.

**Comment by josh-collinsworth** [comment]
Looks like this is an issue with Vercel and the static adapter, which was resolved in adapter-static version 1.0.1. I just pushed an update to `package.json` with the new adapter version, and can confirm it now renders properly on Vercel.

**Comment by lakebayagency** [comment]
Awww yeah buddy! Works like a charm!

Thanks!
