### ISSUE TITLE
Atom link in RSS feed

### ISSUE THREAD

**Issue by ZachSaucier** [josh-collinsworth/sveltekit-blog-starter#36]
Hello, thanks for sharing this starter project.

I was looking at the RSS feed code and I saw this:

```
<atom:link href="https://${siteURL}/rss.xml" rel="self" type="application/rss+xml"/>
```

Isn't it supposed to point to the feed itself, which I believe is at `/api/rss.xml`? So should it be:

```
<atom:link href="https://${siteURL}/api/rss.xml" rel="self" type="application/rss+xml"/>
```

?

**Comment by josh-collinsworth** [comment]
Thanks for reporting! Sorry it took me so long to get to this but it's fixed in the latest main.
