### ISSUE TITLE
can you share how to install tailwind? the standard installation as explained in the tailwind site doesn't work

### ISSUE THREAD

**Issue by eyal-gor** [josh-collinsworth/sveltekit-blog-starter#44]

**Comment by megalois** [comment]
Follow the instructions at https://tailwindcss.com/docs/guides/sveltekit
In particular, make sure to:

1. Create a file named src/tailwind.css, with the tailwind directives (step 5).
2. Import that file at src/routes/+layout.svelte, using import "../tailwind.css" (step 6);

Also, make sure vitePreprocess is set up properly in svelte.config.js

**Comment by josh-collinsworth** [comment]
Thanks @megalois!

@gneyal I've just updated the README to reflect the above, and add a couple of notes.
