### ISSUE TITLE
`font: inherit` overrides heading `--accentFont`

### ISSUE THREAD

**Issue by acidtone** [josh-collinsworth/sveltekit-blog-starter#7]
**Problem**: Changing the `--accentFont` CSS Variable does not affect heading `font-family`.

**Root cause**: [Line 7 of `_layout.scss`](https://github.com/josh-collinsworth/sveltekit-blog-starter/blob/6ef1c7fb4fb1f73735813e3403e7c9c758ac8bf3/src/lib/assets/scss/_layout.scss#L7) is causing the headings to inherit from the body text `--primaryFont` CSS Variable.

**Potential Solutions**: 
- Remove Line 7. This fixes the heading font-family issue but may cause other problems?
- Increase the specificity of the `:where` declaration on [Line 3 of `_typography.scss`](https://github.com/josh-collinsworth/sveltekit-blog-starter/blob/6ef1c7fb4fb1f73735813e3403e7c9c758ac8bf3/src/lib/assets/scss/_typography.scss#L3)

**Comment by josh-collinsworth** [comment]
Good spot. Thanks for letting me know! I've changed `:where` to `:is`, which allows the heading styles to override the generic styles.

**Comment by acidtone** [comment]
I knew there was a `scss` fix for that. Not my strongest area :)
